### ISSUE TITLE
need clean up instructions

### ISSUE THREAD

**Issue by linsun** [IBM/istio101#110]
one of the user complained that we need instructions to clean up the machines properly after this course.

**Comment by jjasghar** [comment]
https://github.com/IBM/istio101/pull/114

I believe this fixes this.

**Comment by beemarie** [comment]
@jjasghar cleanup script was great - just used it to clean up & retest the lab.

It didn't delete some of the rules from exercise 5, such as the virtual-service-guestbook, the guestbook-gateway & the new optional  guestbook-ingress.
