### ISSUE TITLE
the server could not find the requested resource (post gatewaies.networking.istio.io)

### ISSUE THREAD

**Issue by youjiez** [IBM/istio101#151]
Hello,
While I am following the course instruction, I got an error as following:
$ kubectl create -f guestbook-gateway.yaml
Error from server (NotFound): error when creating "guestbook-gateway.yaml": the server could not find the requested resource (post gatewaies.networking.istio.io)

Then I tried to upgrade my kubernetes client version, from 1.6.2 to 1.13.4, but this can not solve the problem, any ideas please?

**Comment by youjiez** [comment]
I have installed version v1.10.12, to make it identical to the server version, and problem is solved.

**Comment by Carmon-Lee** [comment]
the bug seems come from the kubectl CLI tool, which use "gatewaies" for plural of "gateway".

https://stackoverflow.com/questions/53670430/error-install-istio-in-gke-the-server-could-not-find-the-requested-resource-p/56815958#56815958
