### ISSUE TITLE
telemetry dashboards do not pop-up

### ISSUE THREAD

**Issue by lee-zhg** [IBM/istio101#173]
In exercise 4,

Command "istioctl dashboard jaeger",
http://localhost:40285
Failed to open browser; open http://localhost:40285 in your browser.

Command "istioctl dashboard grafana",
http://localhost:43261
Failed to open browser; open http://localhost:43261 in your browser.

Command "istioctl dashboard prometheus",
http://localhost:40297
Failed to open browser; open http://localhost:40297 in your browser.

Command "istioctl dashboard kiali",
http://localhost:39133/kiali
Failed to open browser; open http://localhost:39133/kiali in your browser.

**Comment by rvennam** [comment]
If you enter `open http://www.ibm.com/` in your Terminal, does it work?

What machine are you running on? (OS)

**Comment by lee-zhg** [comment]
got a workaround from your personal repo
