### ISSUE TITLE
Workshop review - Free vs. standard cluster

### ISSUE THREAD

**Issue by artberger** [IBM/istio101#43]
I think that it needs to be called out on the main workshop readme which exercises you can complete with a free cluster, and which you'll need a standard cluster to make.

To me, it doesn't make sense to have users invested in the workshop with a free cluster, only to get to like Exercise 4 and not be able to continue and have to redo their setup.

**Comment by linsun** [comment]
Andy, can you clarify in exercise 4, the steps for free tier and paid tier to retrieve istio-ingress?  so that user can do the exercise 4 with the free tier also.

**Comment by szihai** [comment]
But we are not changing the istio.yaml to switch to nodeport. How can free tier have ingress running?

**Comment by szihai** [comment]
@linsun , just tried the nodeport Ingress. IBM cloud has disabled access to node without a "host" header. So if we want to enable nodeport option we need to do like `curl  --header 'Host: www.example.com' ` to bypass lb.

**Comment by linsun** [comment]
hmm, i 'm using nodeport without the host header, and it works okay.  Could accessing the istio-ingress via nodeport like this work?    curl 169.60.77.186:31380/echo/universe
