### ISSUE TITLE
Workshop - clarify if the exercises build upon each other (are prereq's to the next)

### ISSUE THREAD

**Issue by artberger** [IBM/istio101#46]
Are we making the assumption that users will complete ALL the exercises together in a row? 

If there's a path that the user can take, that might be helpful to call out. Like if one Exercise is a stand-alone, but others have pre-req's.

### Examples:
* Exercise 2 assumes that the user has already targeted the CLI to their cluster (which you did in Exercise 1). 
* Exercise 2 mentions:
> **Note**: If you need to enable mutual TLS authentication between sidecars, you can install the `istio-auth` file instead: `kubectl apply -f install/kubernetes/istio-auth.yaml`

* However, in Exercise 8, this isn't given as a pre-req, even though it seems that it would be a pre-req. This would be especially important to call out, because it's given as optional in Exercise 2.

**Comment by linsun** [comment]
Andy, can you check it out, since you own exercise 2 and 8.

**Comment by szihai** [comment]
Hi @artberger , I think you meant Exercise 7 ? Anyway I modified Exercise 2 to install with auth.

**Comment by duglin** [comment]
Closing per @nilesh32's request
