### ISSUE TITLE
Exercise 7

### ISSUE THREAD

**Issue by bhpratt** [IBM/istio101#47]
- Verify AuthPolicy Setting in ConfigMap - What does the user do if the line is commented out?
- Trying out the Authenticated Connection - steps aren't ordered (all #1)
- Disabling Authentication when Things Go Astray - Not sure about "Things go astray"

It looks like this section: Disabling Authentication when Things Go Astray provides info on commenting / uncommenting, but a command should be earlier in the exercise in case things are commented.

I think some intro info that would be useful would be to discuss a scenario where a user might want tls auth inside the cluster. Give the exercise more context.

**Comment by linsun** [comment]
@elevran can you check it out?

**Comment by elevran** [comment]
Yes, sure. Please assign to me (I don't have write access to make this change on the issue)
