### ISSUE TITLE
Exercise 8 where is the mixer rule?

### ISSUE THREAD

**Issue by bhpratt** [IBM/istio101#48]
`istioctl create -f mixer-rule-denial.yaml` But there's no yaml. Is the user supposed to create it? If so, clarify that in steps. And have the YAML as part of the create step.

 Also, seems like it'd be worthwhile to just go ahead and include the file in the GH repo.

**Comment by linsun** [comment]
Andy, can you check it out?

**Comment by duglin** [comment]
Closing per @nilesh32's request
