### ISSUE TITLE
Feedback for exercise 3

### ISSUE THREAD

**Issue by Nadine2016** [IBM/istio101#50]
1. Depending on the knowledge that you think everyone has, maybe it makes sense to explain what the manual injection in istio is. 
2. In "Install the guestbook app with Istio" I would move step 4 after step 1, so that you verify the pods right after you created the app, and then you can concentrate on the service deployment and verifying that the service is up and running. 
3. At the end, you add the watson tone analyzer. But in the beginning it is not mentioned that this is something that you would do in this lesson. 
4. Question: Can you use the watson tone analyzer without binding it to the cluster?
5. It might make sense to explain what guestbook is, maybe just one sentence, so that people understand why you want to analyze the tone. 
6. You also might need to add that you must have the developer role (CF) for the space where you provision the service, to actually be able to do all that.

**Comment by linsun** [comment]
@szihai can you check this out?  ^^

**Comment by duglin** [comment]
Closing per @nilesh32's request
