### ISSUE TITLE
Feedback exercise 5

### ISSUE THREAD

**Issue by Nadine2016** [IBM/istio101#53]
1. I think what could really help here is a description of the included telemetry services that come with istio and the reason why I would want to use any of these. 
2. Not sure if I just did not set it up correctly, but when I was trying to execute `kubectl apply -f install/kubernetes/addons/grafana.yaml`, I was still in the `v2` folder from the previous exercise, so this command did not work for me. 
3. I could not find where the Ingress variable is set that contains the Ingress IP. so the command where you create the workload did not work. Any reason why you do not use the IBM-provided sub domain? 
4. `request-count` did not exist for me, instead I found `istio_double_request_count`
5. I had several commands failing: 

```
ibm$ kubectl port-forward -n istio-system \$(kubectl get pod -n istio-system -l app=jaeger -o \jsonpath='{.items[0].metata.name}') 16686:16686 &
-bash: syntax error near unexpected token `('
```
```
- ibm$ kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=grafana \  -o jsonpath='{.items[0].metadata.name}') 3000:3000
error: name cannot be provided when a selector is specified
error: TYPE/NAME and list of ports are required for port-forward
```

6. Browsing to `http://localhost:8088/dotviz` did not work, although port forwarding was successful
7. Mixer log stream: I did not understand what I am seeing here or what I am looking for after I executed this command.

**Comment by linsun** [comment]
@nilesh32 can you look at the comment above?  ^^

**Comment by nilesh32** [comment]
@szihai Can you please help to fix few issues in https://github.com/IBM/istio101/tree/master/workshop/exercise-5 ? 

The ones I don't know how to fix are below

1. Grafana throws an error below when I run `kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=grafana \  -o jsonpath='{.items[0].metadata.name}') 3000:3000`

error: name cannot be provided when a selector is specified
error: TYPE/NAME and list of ports are required for port-forward
See 'kubectl port-forward -h' for help and examples.

2. Prometheus dashboard doesn't show `istio_request_count`

3. Service graph dashboard doesn't come up

**Comment by szihai** [comment]
I don't have any problems with the commands. Did you take out the "\" in the commands? it was meant to split lines.

**Comment by duglin** [comment]
Closing per @nilesh32's request
