### ISSUE TITLE
Exercise-2 Updates for 0.8

### ISSUE THREAD

**Issue by nilesh32** [IBM/istio101#79]
1. Step-5:Files names have been changed inside Istio directory. Istio.yaml -> Istio-demo.yaml, istio-auth.yaml --> istio-demo-auth.yaml etc. Is this intentional?

https://files.slack.com/files-pri/T27SFGS2W-FB06P77EX/screen_shot_2018-06-01_at_2.17.56_pm.png

2. Step-6: Istio components names are have been changed. Istio-ingress -> istio-ingressgateway. Istio-pilot --> Istio-policy etc. These needs to be updated.

3. Step-7: I don't see Istio-ca getting installed.

**Comment by linsun** [comment]
step 5, as designed, see istio.io quick setup page.  

yes these are the new names.  istio-ca is istio-citadel now.

**Comment by svennam92** [comment]
@Nilesh-Patel addressed #2 with https://github.com/IBM/istio101/pull/88 (a few things left after your commits)
