### ISSUE TITLE
Exercise 4 - Missing File

### ISSUE THREAD

**Issue by svennam92** [IBM/istio101#89]
In [exercise 4](https://github.com/IBM/istio101/tree/master/workshop/exercise-4)
> ### Expose the Guestbook app with Ingress if you have lite cluster
> 1. Configure the guestbook default route with the Istio Ingress controller.
> 
>     ```sh
>     istioctl create -f guestbook-gateway.yaml
>     ```

`guestbook-gateway.yaml` does not exist in the `guestbook` repo. However, there is a `guestbook-gateway.yaml` file in this repo, although I'm not sure if it's the right one: https://github.com/IBM/istio101/blob/master/workshop/plans/guestbook-gateway.yaml

This file should be moved into the `guestbook` repo under the `v2` folder for continuity. Another option is to include an instruction on where to find the file, but that's inconsistent with the "paid" instructions.

I can open a PR with either option - @linsun suggestion?

**Comment by linsun** [comment]
Greg is making major changes to exercise 4, could you hold up this a bit?

**Comment by cboschmans** [comment]
file still missing, above file also not working in cognitiveclass.ai tutorial

**Comment by beemarie** [comment]
This issue can be closed with all the recent updates.

**Comment by beemarie** [comment]
@linsun @duglin - can one of y'all close?

**Comment by linsun** [comment]
Thanks Belinda!
